Change docker db driver
kaiyuanshe/Polyfiller pull request #5
Opened 2024-04-18 15:56 UTC by luojiyin1987

Closed #2 

先用 redis 作为  meta-server 进行测试， redis 停止服务时， metadata就会消失，避免自己再次format 。  不过经过测试 还时报 `<FATAL>: Storage wasb://polyfill4web/myjfs/ is not empty; please clean it up or   pick another volume name [format.go:485]    ` 的报错。 十分不了解  juicefs 的逻辑。  

同时为了   juicefs 可以正常获取释放 fuse， 已经给了 juicefs  privileged 权限， 这是一个高危操作， 十分不理解他们的设计。 

是否可以更换其他的 S3 类中间件， 挂载网络存储到本地磁盘上？

2024-04-20 15:30 UTC, luojiyin1987 commented
![image](https://github.com/kaiyuanshe/Polyfiller/assets/6524977/54056224-e633-47fc-b540-2764fb2e816b)
juicedata/mount:latest   容器已经可以正常运行了

2024-04-20 19:20 UTC, TechQuery requested changes

2024-04-20 19:20 UTC, TechQuery commented on docker-compose.yml
> +      - polyfiller
能否写为一个 service？多行命令写一起，如：

```yml
command: |
    juicefs format
    juicefs mount
```
还有，被依赖的服务写上面，有依赖的写下面。

2024-04-20 19:20 UTC, TechQuery commented on docker-compose.yml
> +
格式化一下

2024-04-21 09:00 UTC, luojiyin1987 commented on docker-compose.yml
> +      - polyfiller
juicefs format  运行完后， 导致容器退出

2024-04-21 09:17 UTC, luojiyin1987 commented
现在是 myjfs 的容器的文件没做持久化， 但 meta-server（postgres）做了数据持久化了。 不知道容器不断启动，是否导致  meta-server 数据混乱，还在测试中。 理想的方案是  myjfs meta-server  都做持久化。 或者 myjfs meta-server  都不做持久化 ，每次都是从新开始。 @TechQuery

2024-04-21 10:47 UTC, TechQuery commented on docker-compose.yml
> +      - polyfiller
> juicefs format  运行完后， 导致容器退出

怎么导致的？

2024-04-21 10:50 UTC, TechQuery commented
> 现在是 myjfs 的容器的文件没做持久化

JuiceFS 的持久化不就只有元数据和文件本身吗？还有哪些要做持久化？

2024-04-21 14:29 UTC, luojiyin1987 commented on docker-compose.yml
> +      - polyfiller
https://github.com/kaiyuanshe/Polyfiller/blob/44005a4943853fab26043a5e5f3f83f010b2eb53/docker-compose.yml#L28

返回退出信息， 导致容器退出运行

2024-04-21 14:30 UTC, luojiyin1987 commented
> > 现在是 myjfs 的容器的文件没做持久化
> 
> JuiceFS 的持久化不就只有元数据和文件本身吗？还有哪些要做持久化？

现在 myjfs 没做容器内挂载文件的持久化， 重新启停后， 就没文件了。

2024-04-21 14:33 UTC, luojiyin1987 commented on docker-compose.yml
> +      - polyfiller
https://github.com/kaiyuanshe/Polyfiller/blob/44005a4943853fab26043a5e5f3f83f010b2eb53/docker-compose.yml#L28

command 运行完成后，返回退出信号， 导致容器退出。 现在这个用法相当于， 我在一个地方 format 好后， 在网络别的地方挂载 juicefs 。

2024-04-26 03:55 UTC, luojiyin1987 commented
我现在越来越倾向用 minio 替换 juiceFS 。 @TechQuery

2024-04-26 07:30 UTC, TechQuery commented
> BlobFuse

这个不能通用于所有对象存储平台，我们不但是自己用，还要通过 PR 给上游提供通用解决方案。

2024-04-26 10:48 UTC, luojiyin1987 commented
https://juicefs.com/en/blog/usage-tips/juicefs-for-docker-data-persistent
看了这篇文章， 我将尝试分步启动 docker 容器 。 @TechQuery

2024-04-27 12:34 UTC, luojiyin1987 commented
> https://juicefs.com/en/blog/usage-tips/juicefs-for-docker-data-persistent 看了这篇文章， 我将尝试分步启动 docker 容器 。 @TechQuery

试了，解决不了。 要不等上游的反馈， 要不更换别的中间件件

2024-04-28 03:58 UTC, luojiyin1987 commented
minio 的运维压力有点大， 考虑 [rclone](https://github.com/rclone/rclone)

2024-04-28 12:02 UTC, TechQuery commented
> minio 的运维压力有点大， 考虑 [rclone](https://github.com/rclone/rclone)

`rclone mount` ？

2024-04-28 13:06 UTC, luojiyin1987 commented
> > minio 的运维压力有点大， 考虑 [rclone](https://github.com/rclone/rclone)
> 
> `rclone mount` ？

https://rclone.org/docker/    它有完整的介绍文档， 在尝试中

2024-05-07 04:38 UTC, luojiyin1987 commented
已经再 rclone 社区 提问
https://forum.rclone.org/t/i-dont-know-how-to-config-azure-china-blob-storage/45887

2024-05-31 03:12 UTC, luojiyin1987 commented
现在的方案 需要在 Linux 安装  fuse   `sudo apt install fuse3 ` 。 目前遇到的问题， rclone docker 容器退出后， 不能 umount 目录。当下次启动会出现的报错， `Error response from daemon: error while creating mount source path '/home/traefik/Polyfiller/metadata': mkdir /home/traefik/Polyfiller/metadata: file exists `  导致 docker compose 启动失败 

解决办法 `sudo umount -l /home/traefik/Polyfiller/metadata`   手动 umount ，就可以正常启动了。 

要解决 docker 退出后， 一些清理工作。

2024-05-31 04:33 UTC, TechQuery requested changes

2024-05-31 04:33 UTC, TechQuery commented on docker-compose.yml
> +    driver: local
卷配置写到上面去。

2024-05-31 04:33 UTC, TechQuery commented on docker-compose.yml
> +      - ./metadata:/metadata:shared # Mount the local directory for the rclone mount
提问：左右两边哪边是定义的卷？

2024-05-31 07:24 UTC, luojiyin1987 commented on docker-compose.yml
> +      - ./metadata:/metadata:shared # Mount the local directory for the rclone mount
右边是定义的卷， 左边是要挂载的本地文件夹。

2024-05-31 11:39 UTC, TechQuery requested changes

2024-05-31 11:39 UTC, TechQuery commented on docker-compose.yml
> +    driver: local
```suggestion
volumes:
  metadata:
    driver: local

networks:
   polyfiller:
```
这样可以和旧的值对比差异。

2024-05-31 11:39 UTC, TechQuery commented on docker-compose.yml
> +    command: "mount azure:/ /metadata --allow-other  --allow-non-empty --vfs-cache-mode writes"
```suggestion
    command: "mount azure:/ /metadata --allow-other --allow-non-empty --vfs-cache-mode writes"
```

2024-05-31 11:39 UTC, TechQuery commented on config/rclone/rclone.conf
> +# get more info  https://rclone.org/install/  && https://rclone.org/docs/
```suggestion
# Detail document in https://rclone.org/install/ & https://rclone.org/docs/

[azure]
type = azureblob
account = xxx
key = xxx
endpoint = https://xxx
```

2024-05-31 16:36 UTC, TechQuery requested changes

2024-05-31 16:36 UTC, TechQuery commented on docker-compose.yml
> +  rclone:
这个服务改回原来的名字

2024-05-31 16:36 UTC, TechQuery commented on docker-compose.yml
> +      - RCLONE_CONFIG=/config/rclone/rclone.conf # Path to the rclone config file inside the container
放到 `container_name` 下面，把差异对比减到最少，让历史记录翻看起来能清晰地知道哪些地方变了。

2024-05-31 16:36 UTC, TechQuery commented on docker-compose.yml
> +      - metadata:/tmp/@wessberg/polyfiller
卷的名字改回去，因为在部署环境有的时候会在一台共享的主机上，尽量命名专用、减少冲突。

2024-05-31 16:40 UTC, TechQuery commented
> 但是对应非正常退出，还是要自己手动清理。

Docker 退出前能否执行 shell 脚本？如果能执行我们自定义的清理逻辑，那下一次启动也就不会报错，也就不会再产生非正常退出了。

2024-05-31 23:26 UTC, TechQuery approved these changes

2024-05-31 23:58 UTC, merged

2024-06-01 00:03 UTC, luojiyin1987 commented
用  Docker volume 挂载到   rclone 容器内，发现  api-service  是无法写入到 volume 里。 即如下配置
```yaml
volumes:
      - ./config/rclone:/config/rclone # Mount the local rclone config directory to the container
      - polyfill-cache:/polyfill-cache:shared # Mount the local directory for the rclone mount
```
后来改成通过本地目录共享的方式解决。有个副作用，`docker compose  down --volumes`  也无法正常  umount， 需要自己手动 umount， 将在下一个迭代解决。  @TechQuery 
 ```yaml
volumes:
      - ./config/rclone:/config/rclone # Mount the local rclone config directory to the container
      - ./polyfill-cache:/polyfill-cache:shared # Mount the local directory for the rclone mount
``` 
和
```yaml
volumes:
      - ./polyfill-cache:/tmp/@wessberg/polyfiller
```