maintain rclone
kaiyuanshe/Polyfiller pull request #6
Opened 2024-06-03 09:53 UTC by luojiyin1987

add  info about rclone in readme,  solve ` Error response from daemon: error while creating mount source path xxx: mkdir  xxx: file exists`  in start-docker.sh

2024-06-05 04:53 UTC, TechQuery requested changes

2024-06-05 04:53 UTC, TechQuery commented on README.md
> +remove old Docker version
```suggestion
###### remove old Docker version
```
（下同）

2024-06-05 04:53 UTC, TechQuery commented on README.md
> +sudo apt install fuse3 -y
使用 Docker 官方一键安装、升级脚本，不要局限于一种 Linux 发行版。

2024-06-05 04:53 UTC, TechQuery commented on start-docker.sh
> +sudo umount "$mount_point"
直接拼接字符串，只用一次的变量不需要声明一大堆。

2024-06-05 07:36 UTC, luojiyin1987 commented on README.md
> +sudo apt install fuse3 -y
https://github.com/docker/docker-install   中说 
` It is not recommended to depend on this script for deployment to production systems.`   。 不同发行版，对方换一下包管理器就行了。

2024-06-05 13:59 UTC, TechQuery commented on README.md
> +sudo apt install fuse3 -y
这个项目也不是私有部署的商业项目，对稳定性要求没那么高。开源项目依赖一个开源的安装脚本为的就是入门尽可能简单，大神有更高的要求，他自然会自己去搞定。

我觉得他官方不推荐用在生产环境，应该是没有那么多精力维护不同的发行版，我之前在华为欧拉上面用过就识别不出来，但主流发行版应该还是稳定的。

2024-06-05 14:29 UTC, luojiyin1987 commented on README.md
> +sudo apt install fuse3 -y
那 boss 主机上的 Docker  版本原来是 24，主流版本现在是25.  脚本使用的源比较落后了。

2024-06-05 16:13 UTC, TechQuery commented on README.md
> +sudo apt install fuse3 -y
> 脚本使用的源比较落后了。 

那说明这个脚本还是以稳定为先的，实在不行我们 fork 一份更新一下软件源 URL。

> 欧拉这种魔改的Linux，出问题是大概率的事。

并没有出问题，只不过脚本提示“识别不了发行版”就直接退出了。

2024-06-06 01:42 UTC, luojiyin1987 commented on README.md
> +sudo apt install fuse3 -y
https://docs.docker.com/engine/release-notes/25.0/    大版本不跟上主流， 要独自面对多少  cve。

2024-06-16 13:52 UTC, TechQuery commented on README.md
> +sudo apt install fuse3 -y
> https://docs.docker.com/engine/release-notes/25.0/    大版本不跟上主流， 要独自面对多少  cve。 

我觉得我们在文本里提供最简洁、通用的安装方式，然后告诉用户如果要安装最新版本，请根据你自己的系统到官方文档的某个链接里去找。

2024-06-18 01:49 UTC, TechQuery requested changes

2024-06-18 01:49 UTC, TechQuery commented on README.md
> +How to configure quickly? use `rclone config` command ? It need knows about a lot of things. Open [Doc](https://rclone.org/docs/), choose a instructions, like [Dropbox](https://rclone.org/dropbox/).
```suggestion
How to configure quickly? Use `rclone config` command? It needs to know a lot of things. Open [Document](https://rclone.org/docs/), choose an instructions, like [Dropbox](https://rclone.org/dropbox/).
```

2024-06-18 01:49 UTC, TechQuery commented on README.md
> +If you use dropbox, in `docker-compose.yml`.
```suggestion
If you use Dropbox in `docker-compose.yml`:
```

2024-06-18 01:49 UTC, TechQuery commented on README.md
> +It should be changed to.
```suggestion
It should be changed to:
```

2024-06-18 01:49 UTC, TechQuery commented on start-docker.sh
> +sudo umount "$mount_point"
```suggestion
# umount polyfill-cache folder
sudo umount "./polyfill-cache"
```

2024-06-18 03:19 UTC, luojiyin1987 commented on README.md
> +the current user joins the docker user group
主要是避免要用 sudo docker  xxx 命令

2024-06-18 03:32 UTC, luojiyin1987 commented on start-docker.sh
> +sudo umount "$mount_point"
umount  mount 操作， 最好用全路径(绝对路径)

2024-06-18 04:19 UTC, TechQuery commented on start-docker.sh
> +sudo umount "$mount_point"
> umount  mount 操作， 最好用全路径(绝对路径)

那写成一行就行了，用一次也没多长，就不用声明变量了。

2024-06-18 17:07 UTC, TechQuery requested changes

2024-06-18 17:07 UTC, TechQuery commented on README.md
> +More info see the [Docker install Doc](https://docs.docker.com/engine/install/).
```suggestion
You need to press <kbd>CTRL</kbd> + <kbd>D</kbd> to log out of the session, then use SSH to log back into the system.

[Docker-install-script](https://github.com/docker/docker-install) says `It is not recommended to depend on this script for deployment to production systems`. **So depend on your choice**.

Find more information in the [Docker install document](https://docs.docker.com/engine/install/).
```

2024-06-18 17:07 UTC, TechQuery commented on README.md
>        - [Simple container](#simple-container)
安装章节标题级别缩进去了

2024-06-19 18:51 UTC, TechQuery approved these changes

2024-06-19 18:52 UTC, merged