get config from service-configuartion
kaiyuanshe/Polyfiller pull request #7
Opened 2024-06-05 03:11 UTC by luojiyin1987

2024-06-05 04:55 UTC, TechQuery requested changes

2024-06-05 04:55 UTC, TechQuery commented on package.json
> +		"install:config":  "get-git-folder https://github.com/kaiyuanshe/service-configuration main Polyfiller  ||  true"
```suggestion
		"install":  "get-git-folder https://github.com/kaiyuanshe/service-configuration main Polyfiller  ||  true"
```
用 NPM 预定义的脚本名会在相应的生命周期自动执行。

2024-06-05 14:00 UTC, TechQuery requested changes

2024-06-05 14:00 UTC, TechQuery commented on package.json
> +		"install":  "get-git-folder https://github.com/kaiyuanshe/service-configuration main Polyfiller  ||  true"
```suggestion
		"install": "get-git-folder https://github.com/kaiyuanshe/service-configuration main Polyfiller  ||  true"
```

2024-06-06 01:46 UTC, luojiyin1987 commented on package.json
> +		"install":  "get-git-folder https://github.com/kaiyuanshe/service-configuration main Polyfiller  ||  true"
下次还是手动格式化。vscode 的保存后自动格式化，不是每个都成功运行。

2024-06-16 13:49 UTC, TechQuery commented on package.json
> +		"install":  "get-git-folder https://github.com/kaiyuanshe/service-configuration main Polyfiller  ||  true"
> vscode 的保存后自动格式化，不是每个都成功运行。

我从来都是用项目里的 Git hook

2024-06-19 18:54 UTC, TechQuery commented
一起同步一下 `master` 分支的更新。

2024-06-20 02:58 UTC, TechQuery requested changes

2024-06-20 02:58 UTC, TechQuery commented on docker-compose.yml
> +  polyfiller:
```suggestion
```

我们集中式部署不需要专用网络。

2024-06-20 02:58 UTC, TechQuery commented on docker-compose.yml
> +    restart: always
```suggestion
```
你说过集中式部署全局只需要一个健康监控就行了。

2024-06-20 02:58 UTC, TechQuery commented on docker-compose.yml
> +    command: caddy reverse-proxy --from polyfiller.app --to api-service:3000
```suggestion
```
集中式部署有统一的反向代理。

2024-06-20 03:22 UTC, TechQuery commented
@luojiyin1987 在这个分支上打一个形如 `v0.2.3-oss-test-0` 的 tag，让它在服务器部署一下，看拉起来正不正常。

2024-06-20 03:48 UTC, TechQuery requested changes

2024-06-20 03:48 UTC, TechQuery commented on Dockerfile
> +    apt-get install git curl -y --no-install-recommends
你装了也没有 GitHub 登录权限，私有库照样拉不下来，照样报错。

但实际那个错误在生产环境一直是抑制的，配置文件是通过 GitHub actions secret 注入的。

2024-06-20 04:22 UTC, TechQuery requested changes

2024-06-20 04:22 UTC, TechQuery commented on package.json
> +		"get-git-folder": "^0.1.2"
它目前只给开发用，生产环境是用 secret 注入环境变量。

2024-06-20 08:19 UTC, TechQuery requested changes

2024-06-20 08:19 UTC, TechQuery commented on Dockerfile
> +    apt-get install  curl -y --no-install-recommends
新增的空格没删干净。

2024-06-20 09:05 UTC, TechQuery requested changes

2024-06-20 09:05 UTC, TechQuery commented on config/rclone/rclone.conf
> +# Detail document in https://rclone.org/install/ & https://rclone.org/docs/
参考以下代码，写一个从 action secret 注入配置文件的命令：
https://github.com/kaiyuanshe/Polyfiller/blob/17ab0c085ab49a9e6390cc9934a3bc0c9a226391/.github/workflows/deploy-oss.yml#L38-L40

2024-06-21 05:13 UTC, TechQuery requested changes

2024-06-21 05:13 UTC, TechQuery commented on .github/workflows/deploy-oss.yml
> +                  mv config/ build/
在上一步一并注入、移动即可

2024-06-21 05:13 UTC, TechQuery commented on README.md
> +| `RCLONE_FILE` |     rclone configuration file     |
```suggestion
|  `ENV_FILE`   |      `.env` file shown above      |
| `RCLONE_FILE` |     RClone configuration file     |
|    `HOST`     | IP or Domain Name of Cloud Server |
|    `USER`     |   Account Name of Cloud Server    |
|   `SSH_KEY`   |  SSH Private Key of Cloud Server  |
```

2024-06-22 15:43 UTC, TechQuery requested changes

2024-06-22 15:43 UTC, TechQuery commented on .github/workflows/deploy-oss.yml
> +                  mv config/ build/
```suggestion
                  echo "${{ secrets.RCLONE_FILE }}" > config/rclone/rclone.conf
                  mkdir build
                  mv ${{ env.ARTIFACT_PATH }} docker-compose.yml .env config/ start-docker.sh build/
```

2024-06-23 01:03 UTC, TechQuery approved these changes

2024-06-23 01:05 UTC, merged

2024-06-23 01:08 UTC, TechQuery commented
@luojiyin1987 把注入 config 的代码也同步到主分支。